import Head from 'next/head';
import {
  AboutSection,
  FooterSection,
  GallerySection,
  HeroSection,
  ReviewsSection,
  ServicesSection,
} from '../sections';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AboutSection />
      <ServicesSection />
      <GallerySection />
      <ReviewsSection />
      <FooterSection />
    </>
  );
}
