export { HeroSection } from './HeroSection/HeroSection';
export { AboutSection } from './AboutSection/AboutSection';
export { CoursesSection } from './CoursesSection/CoursesSection';
export { FAQSection } from './FAQSection/FAQSection';
export { ServiceSection } from './ServiceSection/ServiceSection';
export { ReviewsSection } from './ReviewsSection/ReviewsSection';
export { FooterSection } from './FooterSection/FooterSection';
export { WorkInProgressSection } from './WorkInProgressSection/WorkInProgressSection';
export { PriceSection } from './PriceSection/PriceSection';
